weather app :
Dmitry-Nikishov/ios_app_interface pull request #46
Opened 2022-01-10 17:50 UTC by Dmitry-Nikishov

- layout finished 90% (only charts missing)

2022-02-14 15:22 UTC, Dmitry-Nikishov commented
full-featured app

2022-02-19 13:22 UTC, denisnzrk requested changes

2022-02-19 13:22 UTC, denisnzrk commented on WeatherApp/WeatherApp/Coordinator/DaySummaryCoordinator.swift
> +        if let vc = daySummaryController as? DaySummaryController {
[Опционально]

Можно подумать как избавиться от этого каста. Не критично, но можно :)

2022-02-19 13:22 UTC, denisnzrk commented on WeatherApp/WeatherApp/Coordinator/MainCoordinator.swift
> +        let controller = viewModelFactory.createViewModel(with: .mainViewModel, coordinator: self)
`ViewModelFactory` создает `ViewController`.
Нужно бы поправить название методов/фабрик в таком случае :) 
Сейчас есть несовпадение)

2022-02-19 13:22 UTC, denisnzrk commented on WeatherApp/WeatherApp/DB/GeoPointsDb.swift
> +    dynamic var id: String?
[Замечание]
тут лучше избавиться от опционалов.
Модель не может существовать без id :)

2022-02-19 22:20 UTC, merged